config/routes.rb
Rails.application.routes.draw do
  resources :players

  devise_for :wusers, :controllers => {:registrations => "wusers/registrations", 
                                       :sessions => "wusers/custom_sessions"}
  
	
  get 'users/new' => 'wusers#new'

  root 'welcome#index'
  get 'admin' => 'admin#admin'
  get 'login' => 'admin#login'
  get 'profile' => 'admin#profile'
	

end

app/models/events.rb
class Events < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :wuser
end

app/models/player_rounds.rb
class PlayerRounds < ActiveRecord::Base
end

app/models/points_audits.rb
class PointsAudits < ActiveRecord::Base
end

app/models/rounds.rb
class Rounds < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/wuser.rb
class Wuser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :player
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_wuser!
  before_filter :isAdmin?
  
  def login
    render "admin/login"
  end

  def isAdmin?
    if current_wuser.isAdmin?
      true
    else
      render :text => 'You must be an admin to do this. If you are recieving this as an error,
                        please contact the E2 Wellness committee.'
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #
  protect_from_forgery with: :exception
	
  def respond_modal_with(*args, &blk)
  	options = args.extract_options!
  	options[:responder] = ModalResponder
  	respond_with *args, options, &blk
  end
end

app/controllers/modalResponder_controller.rb
class ModalResponder < ActionController::Responder
  cattr_accessor :modal_layout
  self.modal_layout = 'modal'

  def render(*args)
    options = args.extract_options!
    if request.xhr?
      options.merge! layout: modal_layout
    end
    controller.render *args, options
  end

  def default_render(*args)
    render(*args)
  end

  def redirect_to(options)
    if request.xhr?
      head :ok, location: controller.url_for(options)
    else
      controller.redirect_to(options)
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_wuser!
  before_filter :isAdmin?
  respond_to :html

  def index
    @players = Player.all
	@player = Player.new
	respond_with(@player, @players)
  end

  def show
    respond_with(@player)
  end

  def new
    @player = Player.new
    respond_with(@player)
  end

  def edit
  end

  def create
    @player = Player.new(player_params)
    #try and find a wuser to connect the player to
    @wuserConnect = Wuser.find_by email: @player.shoptechEmail
    if @wuserConnect != nil
      @player.wuser_id = @wuserConnect.id
      @wuserConnect.isPlayerConnected = true
      @player.save
      @wuserConnect.save
    else
      @player.save
    end
    #respond_with(@player)
	  redirect_to action: "index"
  end

  def update
    @player.update(player_params)
    respond_with(@player)
  end

  def destroy
    @player.destroy
    respond_with(@player)
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:fullName, :points, :shoptechEmail)
    end
	
	def isAdmin?
    	if current_wuser.isAdmin?
      		true
    	else
      		render :text => 'You must be an admin to do this. If you are recieving this as an error,
                        please contact the E2 Wellness committee.'
   		end
   end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wusers/registrations_controller.rb
class Wusers::RegistrationsController < Devise::RegistrationsController
  
  before_filter :configure_permitted_parameters

  protected
  
  # allows custom parameters for devise
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :isAdmin, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
  # put sign_up code here
 #def after_sign_up_path_for(resource)

 # end
end 

app/controllers/wusers/wusers_controller.rb
class UsersController < ApplicationController

  def index
	  @wuser = current_wuser
	  if @wuser.isPlayerConnected
		  foo = "yup"
	  else
		  foo = "nope"
	  end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/admin.html.erb
<h1>Admin Panel</h1>

<div class="col-md-6">
    <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Lifetime Points</th>
        <th>Current Points</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Column content</td>
        <td>Column content</td>
        <td>Column content</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Column content</td>
        <td>Column content</td>
        <td>Column content</td>
      </tr>
      <tr class="info">
        <td>3</td>
        <td>Column content</td>
        <td>Column content</td>
        <td>Column content</td>
      </tr>
      <tr class="success">
        <td>4</td>
        <td>Column content</td>
        <td>Column content</td>
        <td>Column content</td>
      </tr>
      <tr class="danger">
        <td>5</td>
        <td>Column content</td>
        <td>Column content</td>
        <td>Column content</td>
      </tr>
      <tr class="warning">
        <td>6</td>
        <td>Column content</td>
        <td>Column content</td>
        <td>Column content</td>
      </tr>
      <tr class="active">
        <td>7</td>
        <td>Column content</td>
        <td>Column content</td>
        <td>Column content</td>
      </tr>
		</tbody>
  </table> 
</div>
<div class="col-md-6">
		<%= link_to login_path, class: "btn btn-default" do %>
    		<i class="glyphicon glyphicon-scale"> Add Event</i>
		<% end %>
		<br></br>	  
		<%= link_to login_path, class: "btn btn-default" do %>
    		<i class="glyphicon glyphicon-plus"> Add Points</i>
		<% end %>
		<br></br>
		<%= link_to new_player_path, data: { modal: true} , class: "btn btn-default" do %>
    		<i class="glyphicon glyphicon-user"> Add Player</i>
		<% end %>
		<br></br>
</div>

app/views/admin/login.html.erb
<H1>LOGIN</H1>

<div class="col-md-6">
  <form class="form-horizontal">
    <fieldset>
      <legend>New User</legend>
      <div class="form-group">
        <label for="inputEmail" class="col-lg-2 control-label">Email</label>
        <div class="col-lg-10">
          <input type="text" class="form-control" id="inputEmail" placeholder="Email">
        </div>
      </div>
      <div class="form-group">
        <label for="inputPassword" class="col-lg-2 control-label">Password</label>
        <div class="col-lg-10">
          <input type="password" class="form-control" id="inputPassword" placeholder="Password">
          <div class="checkbox">
            <label>
              <input type="checkbox"> Checkbox
            </label>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="textArea" class="col-lg-2 control-label">Textarea</label>
        <div class="col-lg-10">
          <textarea class="form-control" rows="3" id="textArea"></textarea>
          <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Radios</label>
        <div class="col-lg-10">
          <div class="radio">
            <label>
              <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
              Option one is this
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
              Option two can be something else
            </label>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="select" class="col-lg-2 control-label">Selects</label>
        <div class="col-lg-10">
          <select class="form-control" id="select">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>
          <br>
          <select multiple="" class="form-control">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <button type="reset" class="btn btn-default">Cancel</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </fieldset>
  </form>
</div>

app/views/admin/profile.html.erb
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
           <A href="edit.html" >Edit Profile</A>

        <A href="edit.html" >Logout</A>
       <br>
<p class=" text-info">May 05,2014,03:00 pm </p>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Jacob Millner</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100" class="img-circle"> </div>
                
                <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Department:</td>
                        <td>Programming</td>
                      </tr>
                      <tr>
                        <td>Hire date:</td>
                        <td>06/23/2013</td>
                      </tr>
                      <tr>
                        <td>Total Points:</td>
                        <td>230 WP</td>
                      </tr>
                   
                         <tr>
                             <tr>
                        <td>Lifetime Points:</td>
                        <td>500 WP</td>
                      </tr>
                        <tr>
                        <td>Most Recent Redemption:</td>
                        <td>-270 WP Fitbit</td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><a href="mailto:info@support.com">info@support.com</a></td>
                      </tr>
<!--                         <td>Phone Number</td>
                        <td>123-4567-890(Landline)<br><br>555-4567-890(Mobile)
                        </td> -->
                           
                      </tr>
                     
                    </tbody>
                  </table>
                  
                  <a href="#" class="btn btn-primary">Veiw Point History</a>
                  <a href="#" class="btn btn-primary">Redeem Points</a>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>
            
          </div>
        </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "e2_wellness" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "united", :media => "all" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>

    <%= yield %>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <a class="navbar-brand" href="#">
            <%= image_tag("logo_3.png", :alt => "Shoptech Software")%>
            </a>
        </div>
        <div class="navbar-brand">Wellness Portal</div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'News', root_path %></li>
        <% if wuser_signed_in? %>
			  <li><%= link_to 'Profile', profile_path %></li>
            <li><a href="#contact">About</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Login Test', login_path %></li>
                <li><%= link_to 'Admin Test', admin_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
              </li>
              <% if current_wuser.isAdmin %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Login Test', login_path %></li>
                <li><%= link_to 'Admin Test', admin_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
              </li>
            <% end %>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">         
            <% if wuser_signed_in? %>
              <div class="navbar-brand"><li>Hello,  <%= current_wuser.name %> </li></div>
            <li> <%= link_to 'Log Out', destroy_wuser_session_path, :method => :delete %></li>
          <% else %>
            <li> <%= link_to 'Log In', new_wuser_session_path %></li>
            <li> <%= link_to 'Sign Up', new_wuser_registration_path %></li>
          <% end %>
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "united" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>