config/routes.rb
Rails.application.routes.draw do
  resources :players

  devise_for :wusers, :controllers => {:registrations => "wusers/registrations", 
                                       :sessions => "wusers/custom_sessions"}
  
	
  get 'users/new' => 'wusers#new'

  root 'welcome#index'
  get 'admin' => 'admin#admin'
  get 'login' => 'admin#login'
  get 'profile' => 'admin#profile'
	

end

app/models/events.rb
class Events < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :wuser
end

app/models/player_rounds.rb
class PlayerRounds < ActiveRecord::Base
end

app/models/points_audits.rb
class PointsAudits < ActiveRecord::Base
end

app/models/rounds.rb
class Rounds < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/wuser.rb
class Wuser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :player
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_wuser!
  before_filter :isAdmin?
  
  def login
    render "admin/login"
  end

  def isAdmin?
    if current_wuser.isAdmin?
      true
    else
      render :text => 'You must be an admin to do this. If you are recieving this as an error,
                        please contact the E2 Wellness committee.'
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #
  protect_from_forgery with: :exception
	
  def respond_modal_with(*args, &blk)
  	options = args.extract_options!
  	options[:responder] = ModalResponder
  	respond_with *args, options, &blk
  end
end

app/controllers/modalResponder_controller.rb
class ModalResponder < ActionController::Responder
  cattr_accessor :modal_layout
  self.modal_layout = 'modal'

  def render(*args)
    options = args.extract_options!
    if request.xhr?
      options.merge! layout: modal_layout
    end
    controller.render *args, options
  end

  def default_render(*args)
    render(*args)
  end

  def redirect_to(options)
    if request.xhr?
      head :ok, location: controller.url_for(options)
    else
      controller.redirect_to(options)
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_wuser!
  before_filter :isAdmin?
  respond_to :html

  def index
    @players = Player.all
	@player = Player.new
	respond_with(@player, @players)
  end

  def show
    respond_with(@player)
  end

  def new
    @player = Player.new
    respond_with(@player)
  end

  def edit
  end

  def create
    @player = Player.new(player_params)
    #try and find a wuser to connect the player to
    @wuserConnect = Wuser.find_by email: @player.shoptechEmail
    if @wuserConnect != nil
      @player.wuser_id = @wuserConnect.id
      @wuserConnect.isPlayerConnected = true
      @player.save
      @wuserConnect.save
    else
      @player.save
    end
    #respond_with(@player)
	  redirect_to action: "index"
  end

  def update
    @player.update(player_params)
    respond_with(@player)
  end

  def destroy
    @player.destroy
    respond_with(@player)
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:fullName, :points, :shoptechEmail)
    end
	
	def isAdmin?
    	if current_wuser.isAdmin?
      		true
    	else
      		render :text => 'You must be an admin to do this. If you are recieving this as an error,
                        please contact the E2 Wellness committee.'
   		end
   end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wusers/custom_sessions_controller.rb
class Wusers::CustomSessionsController < Devise::SessionsController
  before_filter :before_login, :only => :create
  after_filter :after_login, :only => :create

  def before_login

  end

  def after_login

  end

end

app/controllers/wusers/registrations_controller.rb
class Wusers::RegistrationsController < Devise::RegistrationsController
  
  before_filter :configure_permitted_parameters

  protected
  
  # allows custom parameters for devise
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :isAdmin, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
  # put sign_up code here
 #def after_sign_up_path_for(resource)

 # end
end 

app/controllers/wusers/wusers_controller.rb
class UsersController < ApplicationController

  def index
	  @wuser = current_wuser
	  if @wuser.isPlayerConnected
		  foo = "yup"
	  else
		  foo = "nope"
	  end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fullName, :class => 'control-label' %><br>
    <%= f.text_field :fullName, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :points, :class => 'control-label' %><br>
    <%= f.number_field :points, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :shoptechEmail, :class => 'control-label' %><br>
    <%= f.text_field :shoptechEmail, :class => 'form-control' %>
  </div>
  <div class="actions">
	  <%= f.submit :class => 'btn btn-primary' %>
	  <%= f.submit 'Cancel', :class => "btn btn-default", :data => { :dismiss => 'modal' }, :onclick => "form_submitted = true; return false;"%>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Points</th>
      <th>Shoptechemail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.fullName %></td>
        <td><%= player.points %></td>
        <td><%= player.shoptechEmail %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
		<!-- TODO: Change to if statement to check if connected -->
		<td>Connect to User</td>
		<td>Add Points</td>
		<td>Remove Points</td>
		<td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

<a data-toggle="modal" href="#myModal" class="btn btn-primary">Add Player</a>
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Add Player</h4>
        </div><div class="container"></div>
        <div class="modal-body">
			
			<%= render 'form' %>

        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

app/views/players/new.html.erb
<%= render 'form' %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @player.fullName %>
</p>

<p>
  <strong>Points:</strong>
  <%= @player.points %>
</p>

<p>
  <strong>Shoptechemail:</strong>
  <%= @player.shoptechEmail %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/welcome/index.html.erb
<h1>News:</h1>
<div class="col-md-6">
  <H2>02.12.14</H2>
High Life normcore four loko, gastropub keytar Tumblr mumblecore scenester. Fashion axe put a bird on it Odd Future, fap fanny pack Tumblr pork belly kitsch. Meh flannel keffiyeh tattooed meggings kogi. Locavore Intelligentsia chillwave, meditation tofu tote bag PBR&B literally cred post-ironic swag. Leggings cornhole pork belly, try-hard Austin authentic kogi pop-up Pitchfork normcore trust fund. Letterpress Odd Future hella, deep v heirloom migas umami iPhone roof party. Fixie bitters sustainable DIY, wayfarers +1 hashtag.

Shabby chic fanny pack twee occupy pickled keytar. Leggings stumptown master cleanse locavore sriracha. Paleo salvia you probably haven't heard of them, gentrify put a bird on it Williamsburg tousled pork belly selvage bicycle rights twee. Tofu stumptown meditation heirloom. Before they sold out keffiyeh normcore Banksy. Jean shorts PBR plaid Kickstarter pickled trust fund. Disrupt Intelligentsia Godard, listicle 90's readymade seitan next level fanny pack taxidermy mumblecore.

Leggings Blue Bottle meditation 3 wolf moon forage, tote bag keffiyeh. Bicycle rights roof party tilde iPhone put a bird on it. Irony raw denim PBR, deep v lomo pickled cray four loko tattooed. Kickstarter selvage bicycle rights 8-bit, mixtape bespoke DIY lomo. Cornhole slow-carb yr 8-bit Schlitz YOLO. Wayfarers ugh flexitarian High Life locavore occupy listicle Neutra. Mixtape umami church-key single-origin coffee meggings blog, gentrify salvia flannel sustainable scenester.

Umami four loko salvia, PBR&B four dollar toast Neutra taxidermy Kickstarter cold-pressed scenester kitsch next level retro meh. Bitters seitan dreamcatcher, shabby chic before they sold out meh health goth readymade Tumblr wayfarers. Distillery ennui paleo, farm-to-table raw denim disrupt Wes Anderson literally Echo Park bicycle rights chambray tofu gastropub listicle. Fingerstache cliche tofu, small batch normcore Vice kale chips gluten-free farm-to-table cardigan street art health goth artisan tote bag PBR. Gluten-free freegan selvage forage Schlitz, PBR&B irony jean shorts artisan 90's ugh. Forage skateboard food truck, twee Portland Marfa XOXO 3 wolf moon 8-bit plaid try-hard. Tilde wolf Thundercats pour-over, tofu Blue Bottle sartorial drinking vinegar.
  
  <H2>01.12.14</H2>
  Art party selvage direct trade gentrify, letterpress Tumblr DIY Etsy XOXO squid flannel pork belly. Pop-up biodiesel single-origin coffee drinking vinegar. Narwhal pop-up synth, whatever Shoreditch cornhole fashion axe biodiesel forage four dollar toast put a bird on it keffiyeh small batch VHS next level. Meggings mixtape quinoa pop-up hashtag Vice, tattooed PBR&B authentic ugh. Flannel tofu gluten-free forage, tilde wolf mumblecore street art meggings synth banh mi deep v scenester squid four loko. XOXO mixtape fap, Truffaut letterpress ennui Shoreditch chambray vinyl trust fund pop-up single-origin coffee crucifix tote bag Pitchfork. Raw denim biodiesel flannel literally Williamsburg, skateboard YOLO iPhone Schlitz VHS typewriter hashtag.

90's hoodie kale chips, health goth lo-fi four dollar toast Blue Bottle Brooklyn disrupt fanny pack. Shabby chic Tumblr forage, beard tilde fingerstache hashtag umami squid quinoa Godard Odd Future 90's scenester. Literally hashtag asymmetrical pork belly gastropub mlkshk sustainable. Fingerstache flannel lumbersexual 3 wolf moon. Retro drinking vinegar +1 fixie stumptown, Truffaut Brooklyn lo-fi distillery. Pickled next level ethical, literally twee single-origin coffee Vice flexitarian dreamcatcher migas organic ugh keytar direct trade street art. Meditation sustainable tofu kitsch try-hard, twee Odd Future post-ironic.

Skateboard wolf gentrify PBR&B, vegan post-ironic disrupt authentic gastropub tousled. Cliche organic trust fund vegan retro. McSweeney's cardigan chillwave, lo-fi Schlitz small batch fingerstache actually ugh fixie retro. McSweeney's Marfa stumptown fap tattooed. Fap selfies semiotics salvia Echo Park, forage shabby chic tilde meggings banjo Blue Bottle. Typewriter Godard bicycle rights American Apparel hoodie swag, Helvetica Odd Future polaroid Portland master cleanse cold-pressed. Wes Anderson synth butcher pork belly, Banksy Brooklyn flannel Blue Bottle asymmetrical.

Mustache irony cornhole, tattooed Kickstarter health goth photo booth try-hard McSweeney's Thundercats pickled Tumblr. Ennui fashion axe single-origin coffee, keffiyeh PBR&B retro bespoke readymade 8-bit. Pitchfork quinoa raw denim narwhal. Photo booth semiotics Thundercats, Truffaut pork belly umami fashion axe Tumblr authentic PBR&B DIY High Life. Bespoke High Life sriracha YOLO gentrify. Typewriter chillwave plaid High Life art party, Williamsburg paleo skateboard. 3 wolf moon taxidermy normcore Banksy flexitarian, keytar four dollar toast farm-to-table flannel vinyl Etsy semiotics 8-bit.
</div>

app/views/wusers/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>